import MainApp from "./components/MainApp";
import fs from "fs/promises";
import path from "path";
import { Store } from "./types";

export default async function Home() {
  // Read data.json generated by the crawler
  let stores: Store[] = [];
  try {
    const filePath = path.join(process.cwd(), "public", "data.json");
    const fileContent = await fs.readFile(filePath, "utf-8");
    stores = JSON.parse(fileContent);
  } catch (error) {
    console.error("Failed to load store data:", error);
  }

  return (
    <main className="h-screen w-full overflow-hidden bg-[var(--background)]">
      <MainApp initialStores={stores} />
    </main>
  );
}
